kind: Deployment
apiVersion: apps/v1
metadata:
  name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: jp.icr.io/cti-roks-training/cicd-app1:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: for-ibm-cr
---
kind: Service
apiVersion: v1
metadata:
  name: app1
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app1
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: app1
spec:
  to:
    kind: Service
    name: app1
  tls:
    termination: edge
  port:
    targetPort: http-8080
